# Bind {lan-ip}.silent.vpn and silent.vpn to the current LAN IPv4 via dnsmasq.

. "$SV_LIB/common.sh"

SV_DNSMASQ_SNIPPET="/tmp/dnsmasq.d/silent-vpn.conf"

sv_lan_apply_dns() {
	local ip host
	ip="$(sv_lan_ip)"
	sv_is_ipv4 "$ip" || return 1
	host="${ip}.${SV_ZONE}"
	mkdir -p /tmp/dnsmasq.d
	{
		echo "# generated by silent-vpn — do not edit"
		echo "address=/${host}/${ip}"
		echo "address=/${SV_ZONE}/${ip}"
	} > "$SV_DNSMASQ_SNIPPET"
	uci -q delete dhcp.@dnsmasq[0].address
	uci -q add_list dhcp.@dnsmasq[0].address="/${host}/${ip}"
	uci -q add_list dhcp.@dnsmasq[0].address="/${SV_ZONE}/${ip}"
	uci -q commit dhcp
	if [ -x /etc/init.d/dnsmasq ]; then
		/etc/init.d/dnsmasq restart >/dev/null 2>&1 || true
	fi
	sv_log "lan name ${host} -> ${ip}"
}

sv_lan_host_matches() {
	local host
	host="$(echo "$1" | tr 'A-Z' 'a-z' | cut -d: -f1 | sed 's/\.$//')"
	[ "$host" = "$SV_ZONE" ] && return 0
	echo "$host" | grep -q "\.${SV_ZONE}$"
}
