# Bind {lan-ip}.silent.vpn and silent.vpn to the current LAN IPv4 via dnsmasq.

. "$SV_LIB/common.sh"

SV_DNSMASQ_SNIPPET="/tmp/dnsmasq.d/silent-vpn.conf"

sv_lan_apply_dns() {
	local ip host dir conf line addrs addr
	ip="$(sv_lan_ip | tr -d ' \t\r\n')"
	sv_is_ipv4 "$ip" || return 1
	host="${ip}.${SV_ZONE}"
	# OpenWrt 25 reads conf-dir=/tmp/dnsmasq.<id>.d. /tmp/dnsmasq.d is ignored there.
	dir=""
	for conf in /var/etc/dnsmasq.conf.cfg*; do
		[ -f "$conf" ] || continue
		line="$(sed -n 's/^conf-dir=//p' "$conf" | head -n 1)"
		[ -n "$line" ] && dir="$line" && break
	done
	[ -n "$dir" ] || dir="/tmp/dnsmasq.d"
	mkdir -p "$dir"
	{
		echo "# generated by silent-vpn — do not edit"
		echo "address=/${host}/${ip}"
		echo "address=/${SV_ZONE}/${ip}"
		echo "rebind-domain-ok=silent.vpn"
	} > "$dir/silent-vpn.conf"
	SV_DNSMASQ_SNIPPET="$dir/silent-vpn.conf"
	addrs="$(uci -q get dhcp.@dnsmasq[0].address 2>/dev/null || true)"
	for addr in $addrs; do
		case "$addr" in
			*silent.vpn*) uci -q del_list dhcp.@dnsmasq[0].address="$addr" ;;
		esac
	done
	uci add_list dhcp.@dnsmasq[0].address="/${host}/${ip}"
	uci add_list dhcp.@dnsmasq[0].address="/${SV_ZONE}/${ip}"
	uci -q del_list dhcp.@dnsmasq[0].rebind_domain='silent.vpn'
	uci add_list dhcp.@dnsmasq[0].rebind_domain='silent.vpn'
	uci commit dhcp
	if [ -x /etc/init.d/dnsmasq ]; then
		/etc/init.d/dnsmasq restart >/dev/null 2>&1 || true
	fi
	sv_log "lan name ${host} -> ${ip}"
}

sv_lan_host_matches() {
	local host
	host="$(echo "$1" | tr 'A-Z' 'a-z' | cut -d: -f1 | sed 's/\.$//')"
	[ "$host" = "$SV_ZONE" ] && return 0
	echo "$host" | grep -q "\.${SV_ZONE}$"
}
