# RU services via WAN (router analogue of app exclusions).
# DNS → nft set sv_ru → fwmark → table 162 (WAN). Rest stays in WG.

. "$SV_LIB/common.sh"

SV_RU_LIST="${SV_RU_LIST:-$SV_LIB/ru-direct.domains}"
SV_RU_DNS="/tmp/dnsmasq.d/silent-ru.conf"
SV_RU_TABLE="${SV_RU_TABLE:-162}"
SV_RU_MARK="${SV_RU_MARK:-0x162}"
SV_RU_PRIO="${SV_RU_PRIO:-162}"

sv_ru_enabled() {
	[ "$(uci -q get silent-vpn.main.ru_direct 2>/dev/null)" = "1" ]
}

sv_ru_wan_dev() {
	local d
	d="$(ifstatus wan 2>/dev/null | jsonfilter -e '@.l3_device' 2>/dev/null || true)"
	[ -n "$d" ] || d="$(ifstatus wan 2>/dev/null | jsonfilter -e '@.device' 2>/dev/null || true)"
	[ -n "$d" ] || d="$(uci -q get network.wan.device 2>/dev/null || true)"
	[ -n "$d" ] || d="$(uci -q get network.wan.ifname 2>/dev/null || true)"
	[ -n "$d" ] && echo "$d"
}

sv_ru_wan_gw() {
	local g
	g="$(ifstatus wan 2>/dev/null | jsonfilter -e '@.route[0].nexthop' 2>/dev/null || true)"
	[ -n "$g" ] || g="$(ifstatus wan 2>/dev/null | jsonfilter -e '@.inactive.route[0].nexthop' 2>/dev/null || true)"
	[ -n "$g" ] || g="$(uci -q get network.wan.gateway 2>/dev/null || true)"
	[ -n "$g" ] && echo "$g"
}

sv_ru_clear_policy() {
	ip rule del fwmark "$SV_RU_MARK" lookup "$SV_RU_TABLE" 2>/dev/null || true
	ip route flush table "$SV_RU_TABLE" 2>/dev/null || true
	nft flush set inet fw4 sv_ru 2>/dev/null || true
}

sv_ru_ensure_nft() {
	nft list set inet fw4 sv_ru >/dev/null 2>&1 || \
		nft add set inet fw4 sv_ru '{ type ipv4_addr; flags timeout; timeout 1h; }' 2>/dev/null || \
		nft add set inet fw4 sv_ru '{ type ipv4_addr; }' 2>/dev/null || true
	if ! nft list chain inet fw4 silent_ru_mark >/dev/null 2>&1; then
		nft add chain inet fw4 silent_ru_mark '{ type filter hook prerouting priority -150; policy accept; }' 2>/dev/null || true
		nft add rule inet fw4 silent_ru_mark ip daddr @sv_ru meta mark set "$SV_RU_MARK" 2>/dev/null || true
	fi
	if ! nft list chain inet fw4 silent_ru_out >/dev/null 2>&1; then
		nft add chain inet fw4 silent_ru_out '{ type filter hook output priority -150; policy accept; }' 2>/dev/null || true
		nft add rule inet fw4 silent_ru_out ip daddr @sv_ru meta mark set "$SV_RU_MARK" 2>/dev/null || true
	fi
}

sv_ru_ensure_route() {
	local dev gw
	dev="$(sv_ru_wan_dev)" || true
	gw="$(sv_ru_wan_gw)" || true
	[ -n "$dev" ] || return 0
	ip route flush table "$SV_RU_TABLE" 2>/dev/null || true
	if [ -n "$gw" ]; then
		ip route replace default via "$gw" dev "$dev" table "$SV_RU_TABLE" 2>/dev/null || true
	else
		ip route replace default dev "$dev" table "$SV_RU_TABLE" 2>/dev/null || true
	fi
	ip rule del fwmark "$SV_RU_MARK" lookup "$SV_RU_TABLE" 2>/dev/null || true
	ip rule add fwmark "$SV_RU_MARK" lookup "$SV_RU_TABLE" pref "$SV_RU_PRIO" 2>/dev/null || true
}

sv_ru_write_dns() {
	mkdir -p /tmp/dnsmasq.d
	{
		echo "# generated by silent-vpn ru-direct"
		while read -r d || [ -n "$d" ]; do
			echo "$d" | grep -q '^#' && continue
			[ -n "$d" ] || continue
			echo "nftset=/${d}/4#inet#fw4#sv_ru"
		done < "$SV_RU_LIST"
	} > "$SV_RU_DNS"
}

sv_ru_apply() {
	if ! sv_ru_enabled; then
		rm -f "$SV_RU_DNS"
		sv_ru_clear_policy
		/etc/init.d/dnsmasq restart >/dev/null 2>&1 || true
		sv_log "ru-direct off"
		return 0
	fi
	sv_ru_ensure_nft
	sv_ru_ensure_route
	sv_ru_write_dns
	/etc/init.d/dnsmasq restart >/dev/null 2>&1 || true
	sv_log "ru-direct on table=$SV_RU_TABLE mark=$SV_RU_MARK"
}

sv_ru_set() {
	local on="$1"
	uci -q set silent-vpn.main.ru_direct="$on"
	uci -q commit silent-vpn
	sv_ru_apply
}
