/** Generated by scripts/gen_integrity_hashes.js — do not edit by hand. */
module.exports = {
  WDTT_SHA256: '1ad3e88e3b05558132d3cf3fdcce8aa00b375425d2a11982f40da01fe60193b2',
  GENERATED_AT: '2026-08-15T23:34:15.582Z',
}
