/** Generated by scripts/gen_integrity_hashes.js — do not edit by hand. */
module.exports = {
  WDTT_SHA256: '98c1ae332a69d7458d5586d5f670144c991d0e1fa3c984c20dc744dbbe461d4f',
  WDTT_LINUX_SHA256: 'f34399e58f2e65b6f2353e3cc4e260f05391af82730b18cab11e197c1513f9f3',
  GENERATED_AT: '2026-09-04T09:34:51.120Z',
}
