/** Generated by scripts/gen_integrity_hashes.js — do not edit by hand. */
module.exports = {
  WDTT_SHA256: '4be681a3b7b40c57163a1c3dbea9a0012097ebb3de4a50b67fb590676e11a719',
  WDTT_LINUX_SHA256: '44b51558c6ed775694945e3e28d212a463dd030bc77a29e77c3de6dd7884dda1',
  WDTT_MAC_SHA256: 'cd47fdf4470ba84d205cebf55afdbbff4024ca625aeb2f101fc77d97f1b66668',
  GENERATED_AT: '2026-09-18T08:45:54.421Z',
}
