/**
 * Пишет src/main/integrityHashes.js с SHA-256 текущего wdtt-client (Windows и/или Linux).
 * Вызывать после go build в build-installer.bat / build-linux.
 */
const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const root = path.join(__dirname, '..')
const winExe = path.join(root, 'resources', 'wdtt-client.exe')
const linuxExe = path.join(root, 'resources', 'linux', 'wdtt-client')
const out = path.join(root, 'src', 'main', 'integrityHashes.js')

if (!fs.existsSync(winExe) && !fs.existsSync(linuxExe)) {
  console.error('gen_integrity_hashes: wdtt-client not found (windows or linux)')
  process.exit(1)
}

function sha(p) {
  return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')
}

let existing = { WDTT_SHA256: '', WDTT_LINUX_SHA256: '' }
try {
  existing = require(out)
} catch { /* first run */ }

const winHash = fs.existsSync(winExe) ? sha(winExe) : String(existing.WDTT_SHA256 || '')
const linuxHash = fs.existsSync(linuxExe) ? sha(linuxExe) : String(existing.WDTT_LINUX_SHA256 || '')

const body =
  `/** Generated by scripts/gen_integrity_hashes.js — do not edit by hand. */\n` +
  `module.exports = {\n` +
  `  WDTT_SHA256: '${winHash}',\n` +
  `  WDTT_LINUX_SHA256: '${linuxHash}',\n` +
  `  GENERATED_AT: '${new Date().toISOString()}',\n` +
  `}\n`
fs.writeFileSync(out, body, 'utf8')
console.log('integrityHashes.js WDTT_SHA256=', winHash, 'WDTT_LINUX_SHA256=', linuxHash)
