/**
 * Пишет src/main/integrityHashes.js с SHA-256 текущего resources/wdtt-client.exe.
 * Вызывать после go build в build-installer.bat / build-debug.
 */
const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const root = path.join(__dirname, '..')
const exe = path.join(root, 'resources', 'wdtt-client.exe')
const out = path.join(root, 'src', 'main', 'integrityHashes.js')

if (!fs.existsSync(exe)) {
  console.error('gen_integrity_hashes: wdtt-client.exe not found:', exe)
  process.exit(1)
}

const hash = crypto.createHash('sha256').update(fs.readFileSync(exe)).digest('hex')
const body =
  `/** Generated by scripts/gen_integrity_hashes.js — do not edit by hand. */\n` +
  `module.exports = {\n` +
  `  WDTT_SHA256: '${hash}',\n` +
  `  GENERATED_AT: '${new Date().toISOString()}',\n` +
  `}\n`
fs.writeFileSync(out, body, 'utf8')
console.log('integrityHashes.js WDTT_SHA256=', hash)
